server:
  port: 10020
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  redis:
    database: 0
    host: 192.168.23.47
    port: 6379
    ssl: false
    timeout: 1800000ms
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        max-wait: 5000
        min-idle: 5
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/choice?useUnicode=true&connectionCollation=utf8_general_ci&useSSL=false&serverTimezone=Asia/Shanghai&characterSetResults=utf8&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
      username: denglu
      password: denglu
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat
my:
 name: springboot
 age: 12
#JavaBean名字不能大写
configfilebean:
 name: forezp
 age: 13
 number:  ${random.int}
 uuid : ${random.uuid}
 max: ${random.int(10)}
 value: ${random.value}
 greeting: hi,i'm  ${my.name}
